SITEURL = "https://www.corbettclark.com"
SITENAME = "Dr Timothy Corbett-Clark"
SITEDESCRIPTION = "Personal website of Dr Timothy Corbett-Clark"
AUTHOR = "Timothy Corbett-Clark"
GITHUB_URL = "https://github.com/tcorbettclark/tcorbettclark.github.io"
COPYRIGHT_FOOTER = "Timothy Corbett-Clark, 2026"

MY_NAME = "Dr Timothy Corbett&#8209;Clark"
MY_TAGLINE = "CTO, Researcher, Developer"
